# Configuration file for Transcript and Video Automation System

# General Configuration
general:
  output_directory: "./data/output"
  log_level: "info"  # debug, info, warning, error
  
# Transcript Processing Pipeline
transcript:
  # YouTube Transcript API
  youtube:
    language: "en"  # Default language to fetch
    fallback_to_auto_generated: true
  
  # Segmentation
  segmentation:
    max_segment_size: 23000       # Maximum characters per segment
    min_segment_size: 17000       # Minimum characters per segment
    target_segment_size: 20000    # Target characters per segment
    segment_overlap: 1000         # Overlap between segments
    respect_semantic_boundaries: true
    
  # Large Transcript Processing
  large_transcript:
    enabled: true                 # Enable large transcript processing
    threshold: 100000             # Character threshold to use chunked processing
    validate_segment_length: true # Validate segment lengths
    max_retries: 2                # Maximum retries for segment processing
    
  # AI Processing
  ai:
    model: "gemini-flash-lite"  # AI model to use via LiteLLM
    temperature: 0.3
    max_tokens: 8192
    
  # Text-to-Speech
  tts:
    engine: "piper"  # piper, coqui, etc.
    voice: "en_US-lessac-medium"
    output_format: "mp3"
    quality: "high"
    
# Video Compilation Pipeline
video:
  # Sources
  sources:
    - name: "pixabay"
      enabled: true
      priority: 1
    - name: "freepik"
      enabled: true
      priority: 2
      
  # Search
  search:
    default_terms:
      - "nature"
      - "landscape"
      - "water"
      - "sky"
      - "mountain"
    preferred_resolution: "4k"
    
  # Clips
  clips:
    min_duration: 5    # Minimum clip duration in seconds
    max_duration: 25   # Maximum clip duration in seconds
    min_quality: "hd"  # hd, fullhd, 4k
    
  # Compilation
  compilation:
    target_duration: 10800  # 3 hours in seconds
    randomize_order: true
    use_transitions: false  # Add transitions between clips
    
# Final Assembly
assembly:
  video_codec: "libx264"
  audio_codec: "aac"
  output_format: "mp4"
  handle_duration_mismatch: "trim_video"  # trim_video, stretch_audio, none
