[phases.setup]
nixPkgs = ['python311', 'gcc']
nixLibs = ['zlib', 'stdenv.cc.cc.lib']

[variables]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PYTHONDONTWRITEBYTECODE = "1"
NIXPACKS_METADATA = "python"

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install --no-cache-dir -r requirements.txt'
]
dependsOn = ['setup']

[phases.build]
cmds = []

[start]
cmd = 'python main.py' 