version: "3.8"

services:
  backend:
    image: veloxforce/prellus_backend:v0.1.0
    platform: linux/amd64
    container_name: prellus_backend
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 10G
    networks:
      - prellus_network

  frontend:
    image: veloxforce/prellus_frontend:v0.1.0
    container_name: prellus_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - prellus_network

networks:
  prellus_network:
