[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']
nixLibs = ['libuuid', 'libGL']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']

[variables]
CI = "true"
NIXPACKS_METADATA = "node"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ['npm ci']
dependsOn = ['setup']

[phases.build]
cmds = ['npm run build']
dependsOn = ['install']

[start]
cmd = 'npm run start' 